= AWS AMI Marketplace Developer Documentation

This documentation is not meant for end-user consumption, but rather for internal teams working on the XL Platform AMI Marketplace project.

== Executing the tests

Follow these steps to execute tests using AWS TaskCat. 

1. https://aws-quickstart.github.io/install-taskcat.html[Install taskcat]. The included `pipenv` file can be used to do this if you'd like to keep your global context clean. 
2. Modify `ci/new-vpc-e2e.json` and parameters that fits you (you can also use you local `~/.aws/taskcat_global_override.json` to override parameters like `KeyPairName`)
3. Modify `ci/taskcat.yaml` so it can work your your aws account. For example the region has to be the same as the region in your `~/.aws/config`
4. Now we can run `taskcat -c ci/taskcat.yaml`. If you'd like to keep the stack running after the tests have passed *or* failed, run `taskcat -n -c ci/taskcat.yaml`. 

== Cleanup S3 buckets from TaskCat runs

If an error occurred while running TaskCat, or you added the `-n` option, TaskCat doesn't clean up the buckets it creates by default. To clean up these buckets manually, run the following shell command:

``` 
for i in `aws s3 ls | grep taskcat | awk '{print $3}'`; do aws s3 rb s3://$i --force; done
```