AWSTemplateFormatVersion: 2010-09-09
Description: "This template will launch 2 EC2 instances with XL Deploy\n"
Parameters:
  XLDeployInstanceType:
    Description: XL Deploy EC2 instance type
    Type: String
    AllowedValues:
      - t2.medium
      - c5.large
      - c5.xlarge
      - m5.large
      - m5.2xlarge
    ConstraintDescription: must be a valid EC2 instance type.
  ASGInstanceName:
    Description: ASG instances name
    Type: String
    Default: xl-deploy-asg-marketplace
  KeyPairName:
    Description: The EC2 Key Pair to allow SSH access to the instances
    Type: AWS::EC2::KeyPair::KeyName
    ConstraintDescription: must be the name of an existing EC2 KeyPair.
  PrivateSubnetIDs:
    Description: The private subnet XL should be deployed to
    Type: List<AWS::EC2::Subnet::Id>
  XLDeployAdminPassword:
    Description: The admin password of XL Deploy
    MinLength: 8
    Type: String
    NoEcho: true
  XLDeployPort:
    Description: The port to run XL Deploy on
    AllowedPattern: ^[1-9][0-9]{3,4}$
    Type: String
    Default: '4516'
  TargetGroupARN:
    Description: ALB TargetGroup ARN for XL Deploy
    Type: String
  SecurityGroup:
    Type: AWS::EC2::SecurityGroup::Id
    Description: The Security Group that grants access
  DBHost:
    Description: The Postgres DB Host/Endpoint
    Type: String
  DBPort:
    Description: The Postgres DB Port
    Type: String
    Default: 5432
  DBUser:
    Description: The Postgres DB username
    Type: String
  DBPassword:
    Description: The Postgres DB Password
    Type: String
    NoEcho: true
  DBDriver:
    Description: The database driver to use
    Type: String
    Default: org.postgresql.Driver
    AllowedValues:
      - org.postgresql.Driver
      - com.microsoft.sqlserver.jdbc.SQLServerDriver
      - com.mysql.cj.jdbc.Driver
  EfsId:
    Description: The ID of the EFS filesystem within the selected VPC
    Type: String
    AllowedPattern: ^fs\-\w{8,}$
    ConstraintDescription: Must be a valid EFS identifier
  LogGroup:
    Description: The CloudWatch log group to push XL Deploy logs to
    Type: String
    Default: /aws/ec2/xld
  AMIID:
    Description: The AMI ID used to for XL DevoPS Platform
    Type: AWS::EC2::Image::Id
  AWSProductCode:
    Description: The AWS AMI Marketplace Listing Product Code
    Type: String
Mappings:
  DBType:
    org.postgresql.Driver:
      Name: postgresql
    com.microsoft.sqlserver.jdbc.SQLServerDriver:
      Name: sqlserver
    com.mysql.cj.jdbc.Driver:
      Name: mysql
Resources:
  XLDeployGroup:
    Type: AWS::AutoScaling::AutoScalingGroup
    Properties:
      VPCZoneIdentifier:
        Ref: PrivateSubnetIDs
      LaunchConfigurationName:
        Ref: LaunchConfig
      Tags:
        - Key: Name
          PropagateAtLaunch: true
          Value:
            Ref: ASGInstanceName
      MinSize: '2'
      MaxSize: '2'
      TargetGroupARNs:
        - Ref: TargetGroupARN
    CreationPolicy:
      ResourceSignal:
        Timeout: PT10M
        Count: 2
    UpdatePolicy:
      AutoScalingRollingUpdate:
        MinInstancesInService: 1
        MaxBatchSize: 1
        PauseTime: PT10M
        WaitOnResourceSignals: true
  LaunchConfig:
    Type: AWS::AutoScaling::LaunchConfiguration
    Metadata:
      AWS::CloudFormation::Init:
        setup:
          files:
            /opt/xld/conf/deployit.conf:
              content: "admin.password={{XLDeployAdminPassword}}\njcr.repository.path=repository\n\
                threads.min=3\nmaintenance.forbidden_paths=deployit/task\\:POST,deployit/tasks/v2\\\
                :POST,deployit/control\\:POST\nclient.server_poll.delay=30000\nssl=false\n\
                http.bind.address=0.0.0.0\nhttp.context.root=/deploy\nthreads.max=24\n\
                ssl.mutual=false\nhttp.upload.buffer=262144\nhttp.port={{XLDeployPort}}\n\
                client.automatically.map.all.deployables.on.initial=true\nclient.automatically.map.all.deployables.on.update=true\n\
                client.automatically.map.all.deployables=true\nclient.session.timeout.minutes=144\n\
                client.session.remember.enabled=true\nserver.resolve.application.dependencies=true\n\
                server.mapping.override.deployed.fields.on.update=true\nhide.internals=false\n\
                importable.packages.path=importablePackages\n"
              owner: xl
              group: xl
              context:
                XLDeployAdminPassword:
                  Ref: XLDeployAdminPassword
                XLDeployPort:
                  Ref: XLDeployPort
            /opt/xld/conf/xl-deploy.conf:
              content: "xl {\n  metrics {\n    enabled = false\n  }\n\n  license {\n\
                \    product=xl-deploy\n    kind = ami\n    ami {\n      productCode\
                \ = \"{{ AWSProductCode }}\"\n    }\n  }\n\n  cluster {\n    # mode:\
                \ \"default\", \"hot-standby\", \"full\"\n    mode = hot-standby\n\
                \    name = \"xl-deploy_cluster\"\n\n    node {\n        clusterPort=2552\n\
                \        hostname=\"HOSTNAME\"\n        id=\"HOSTNAME\"\n    }\n\n\
                \    membership {\n      jdbc {\n        url=\"jdbc:{{ DBType }}://{{\
                \ DBHost }}:{{ DBPort }}/xldeploy\"\n        username=\"{{ DBUser\
                \ }}\"\n        password=\"{{ DBPassword }}\"\n      }\n    }\n  \
                \  akka {\n      loglevel = \"INFO\"\n      actor.debug.receive =\
                \ off\n      remote {\n        log-received-messages = off\n     \
                \   log-sent-messages = off\n      }\n    }\n  }\n\n  repository {\n\
                \    artifacts {\n      type = \"db\"\n    }\n    database {\n   \
                \   db-driver-classname=\"{{ DBDriver }}\"\n      db-username=\"{{\
                \ DBUser }}\"\n      db-password=\"{{ DBPassword }}\"\n      db-url=\"\
                jdbc:{{ DBType }}://{{ DBHost }}:{{ DBPort }}/xldeploy\"\n      max-pool-size=10\n\
                \    }\n  }\n\n  reporting {\n    database {\n      db-driver-classname\
                \ = \"{{ DBDriver }}\"\n      db-username = \"{{ DBUser }}\"\n   \
                \   db-password = \"{{ DBPassword }}\"\n      db-url = \"jdbc:{{ DBType\
                \ }}://{{ DBHost }}:{{ DBPort }}/xldeploy\"\n      max-pool-size=10\n\
                \    }\n  }\n\n}\n"
              context:
                AWSProductCode:
                  Ref: AWSProductCode
                DBUser:
                  Ref: DBUser
                DBPassword:
                  Ref: DBPassword
                DBHost:
                  Ref: DBHost
                DBPort:
                  Ref: DBPort
                DBDriver:
                  Ref: DBDriver
                DBType:
                  Fn::FindInMap:
                    - DBType
                    - Ref: DBDriver
                    - Name
              owner: xl
              group: xl
            /opt/xld/conf/logback.xml:
              content: "<configuration>\n  <!-- removing this listener may cause performance\
                \ issues-->\n  <contextListener class=\"ch.qos.logback.classic.jul.LevelChangePropagator\"\
                >\n      <resetJUL>true</resetJUL>\n  </contextListener>\n\n  <appender\
                \ name=\"STDOUT\" class=\"ch.qos.logback.core.ConsoleAppender\">\n\
                \      <encoder>\n          <pattern>%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread]\
                \ {%mdc} %-5level %logger{36} - %msg%n</pattern>\n      </encoder>\n\
                \  </appender>\n\n  <appender name=\"FILE\" class=\"ch.qos.logback.core.rolling.RollingFileAppender\"\
                >\n      <file>log/${LOGFILE:-deployit}.log</file>\n      <rollingPolicy\
                \ class=\"ch.qos.logback.core.rolling.FixedWindowRollingPolicy\">\n\
                \          <fileNamePattern>log/${LOGFILE:-deployit}.%i.log</fileNamePattern>\n\
                \          <minIndex>1</minIndex>\n          <maxIndex>5</maxIndex>\n\
                \      </rollingPolicy>\n      <triggeringPolicy class=\"ch.qos.logback.core.rolling.SizeBasedTriggeringPolicy\"\
                >\n          <maxFileSize>5MB</maxFileSize>\n      </triggeringPolicy>\n\
                \      <encoder>\n          <pattern>%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread]\
                \ {%mdc} %-5level %logger{36} - %msg%n</pattern>\n      </encoder>\n\
                \  </appender>\n\n  <appender name=\"CLOUDWATCH\" class=\"io.github.dibog.AwsLogAppender\"\
                >\n      <createLogGroup>true</createLogGroup>\n      <queueLength>100</queueLength>\n\
                \      <groupName>{{LogGroup}}</groupName>\n      <streamName>XLDeploy-${HOSTNAME:-default}</streamName>\n\
                \      <layout>\n          <pattern>[%X{a} %X{b}] %-4relative [%thread]\
                \ %-5level %logger{35} - %msg %n</pattern>\n      </layout>\n  </appender>\n\
                \n  <root level=\"info\">\n      <appender-ref ref=\"STDOUT\" />\n\
                \      <appender-ref ref=\"FILE\" />\n      <appender-ref ref=\"CLOUDWATCH\"\
                \ />\n  </root>\n\n  <logger name=\"com.xebialabs\" level=\"info\"\
                \ />\n  <logger name=\"com.xebialabs.deployit.core.api.resteasy.http\"\
                \ level=\"info\" />\n  <logger name=\"com.xebialabs.deployit.jetty.HttpHeaderOverrideServletRequest\"\
                \ level=\"info\" />\n  <logger name=\"com.xebialabs.deployit.jetty.FlexRestCompatibilityServletRequest\"\
                \ level=\"info\" />\n  <logger name=\"com.xebialabs.deployit.migration\"\
                \ level=\"info\" />\n  <logger name=\"com.xebialabs.overthere\" level=\"\
                info\" />\n  <logger name=\"net.schmizz.sshj\" level=\"error\" />\n\
                \  <logger name=\"org.springframework\" level=\"warn\"/>\n  <logger\
                \ name=\"org.apache.commons.httpclient\" level=\"warn\" />\n  <logger\
                \ name=\"org.apache.jackrabbit.core.value.BLOBInDataStore\" level=\"\
                error\" />\n  <logger name=\"org.eclipse.aether\" level=\"info\" />\n\
                \  <logger name=\"de.schlichtherle.truezip\" level=\"warn\" />\n \
                \ <logger name=\"com.google.inject.internal.util\" level=\"error\"\
                />\n  <logger name=\"org.springframework.beans.factory.support.DefaultListableBeanFactory\"\
                \ level=\"error\"/>\n  <logger name=\"liquibase\" level=\"warn\"/>\n\
                \  <logger name=\"org.springframework.web.socket.adapter.jetty.JettyWebSocketHandlerAdapter\"\
                \ level=\"off\"/>\n\n  <!--  Audit logging -->\n\n  <appender name=\"\
                AUDIT\" class=\"ch.qos.logback.core.rolling.RollingFileAppender\"\
                >\n      <file>log/audit.log</file>\n      <rollingPolicy class=\"\
                ch.qos.logback.core.rolling.TimeBasedRollingPolicy\">\n          <FileNamePattern>log/audit.%d{yyyy-MM-dd}.log</FileNamePattern>\n\
                \      </rollingPolicy>\n      <encoder>\n          <pattern>%d{yyyy-MM-dd\
                \ HH:mm:ss.SSS} [%logger{36}] %msg%n</pattern>\n      </encoder>\n\
                \  </appender>\n  <logger name=\"audit\" level=\"info\" additivity=\"\
                false\">\n      <appender-ref ref=\"AUDIT\" />\n  </logger>\n</configuration>\n"
              owner: xl
              group: xl
              context:
                LogGroup:
                  Ref: LogGroup
          commands:
            00_remove_xlr:
              command: rm -Rf /opt/xlr /etc/systemd/system/xlr.service
            01_configure_wrapper_memory:
              command: export MEMORY=`free -m | head -n 2 | tail -n 1 | awk '{print
                $7}'`; sed -i "s/\[\[ MEM_SIZE \]\]/$MEMORY/" /opt/xld/conf/xld-wrapper-linux.conf
            02_configure_efs_mount:
              command: "mkdir -p $EFS_MOUNT_POINT\necho \"$EFS_ID:/ $EFS_MOUNT_POINT\
                \ efs tls,_netdev\" >> /etc/fstab\nmount -a -t efs defaults\n\nchown\
                \ -R xl:xl $EFS_MOUNT_POINT\n"
              env:
                EFS_ID:
                  Ref: EfsId
                EFS_MOUNT_POINT: /opt/xld/work
            03_get_ip_for_cluster:
              command: export IP=$(curl -s http://169.254.169.254/latest/meta-data/local-ipv4);
                sed -i "s/HOSTNAME/$IP/g" /opt/xld/conf/xl-deploy.conf
          services:
            sysvinit:
              xld:
                enabled: true
                ensureRunning: true
                files:
                  - /opt/xld/conf/xld-wrapper-linux.conf
                  - /opt/xld/conf/xl-deploy.conf
                  - /opt/xld/conf/deployit.conf
                  - /opd/xld/conf/logback.xml
        health_checks:
          commands:
            01_await_healthy_service:
              command: "i=0\nEXIT_CODE=1\n# Let's retry for three minutes (18 times,\
                \ every 10 seconds)\nwhile [ $i -lt 18 ]\ndo\n  echo \"Checking for\
                \ healthy service (currently on attempt $i)...\"\n  RESULT=$(curl\
                \ -s -o /dev/null -w \"%{http_code}\" \"http://localhost:$APPLICATION_PORT/\"\
                )\n\n  if [[ \"$RESULT\" -lt 500 && \"$RESULT\" -ge 200 ]]; then\n\
                \    echo \"Status code is $RESULT - will signal success to stack\"\
                \n    EXIT_CODE=0\n    break\n  else\n    ((i++))\n    echo \"Current\
                \ status code: $RESULT - retrying...\"\n    sleep 30\n  fi\ndone\n\
                \nif [[ \"$EXIT_CODE\" -eq 1 ]]; then\n  echo \"Startup failed - signalling\
                \ failure to stack\"\nfi\n\n/opt/aws/bin/cfn-signal --exit-code $EXIT_CODE\
                \ --stack $STACK_NAME --resource XLDeployGroup --region $REGION\n"
              env:
                APPLICATION_PORT:
                  Ref: XLDeployPort
                STACK_NAME:
                  Fn::Sub: ${AWS::StackName}
                REGION:
                  Fn::Sub: ${AWS::Region}
        jmxtrans:
          commands:
            01_set_asg_name:
              command: sed -i "s/{{ ASG_NAME }}/$ASG_NAME/g" /var/lib/jmxtrans/jmxtrans-cloudwatch.json
              env:
                ASG_NAME:
                  Ref: ASGInstanceName
            02_start_jmxtrans:
              command: sudo systemctl start jmxtrans
        configSets:
          configuration:
            - setup
            - health_checks
            - jmxtrans
    Properties:
      KeyName:
        Ref: KeyPairName
      ImageId:
        Ref: AMIID
      SecurityGroups:
        - Ref: SecurityGroup
      InstanceType:
        Ref: XLDeployInstanceType
      IamInstanceProfile:
        Ref: XLDInstanceProfile
      UserData:
        Fn::Base64:
          Fn::Sub: "#!/bin/bash -xe\nyum update -y aws-cfn-bootstrap\n\n/opt/aws/bin/cfn-init\
            \ -v --stack ${AWS::StackName} --resource LaunchConfig --region ${AWS::Region}\
            \ --configsets configuration\n"
  CloudwatchRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - ec2.amazonaws.com
            Action: sts:AssumeRole
      Path: /
      Policies:
        - PolicyName: xld-cloudwatch-logging
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action: logs:*
                Resource: arn:aws:logs:*:*:*
              - Effect: Allow
                Action: cloudwatch:*
                Resource: '*'
  XLDInstanceProfile:
    Type: AWS::IAM::InstanceProfile
    Properties:
      Path: /
      Roles:
        - Ref: CloudwatchRole
Outputs:
  XLDASGName:
    Description: The name of the XL Deploy Auto-scaling Group
    Value:
      Ref: XLDeployGroup
