Description: >
  Template for auto-scaling in an Applicationload balancer target group.
  The ALB will be used as an A Alias target for a specified Route53 hosted zone. This
  template also showcases Metadata Parameter Grouping, Special AWS Parameter Types,
  and Cloudformation Outputs with Exportswhich can be imported into other templates.

Metadata:
  AWS::CloudFormation::Interface:
    ParameterGroups:
#      - Label:
#          default: Global parameters
#        Parameters:
#          - environment
      - Label:
          default: Application Loadbalancer
        Parameters:
          - LoadBalancerName
          - CertificateArn
          - PublicSubnetIDs
          - TargetGroupNameXLD
          - PortXLD
          - TargetGroupNameXLR
          - PortXLR
      - Label:
          default: VPC
        Parameters:
          - VPCID
          - SecurityGroup
Parameters:
  LoadBalancerName:
    Default: 'xebialabs-lb'
    Description: 'Name of Application LoadBalancer for XebiaLabs software'
    Type: String
  CertificateArn:
    Description: Which ACM certificate to use for the load balancer
    Type: String
  PublicSubnetIDs:
    Default: ''
    Description: Public subnets for the load balancer.
    Type: List<AWS::EC2::Subnet::Id>
  TargetGroupNameXLD:
    Default: xl-deploy-tg
    Description: XL Deploy TargetGroup Name
    Type: String
  PortXLD:
    Default: '4516'
    Description: Which port to use to connect to XL Deploy
    Type: Number  
  TargetGroupNameXLR:
    Default: xl-release-tg
    Description: XL Release TargetGroup Name
    Type: String
  PortXLR:
    Default: '5516'
    Description: Which port to use to connect to XL Release
    Type: Number    
  VPCID:
    Default: ''
    Description: Environment VPCID
    Type: AWS::EC2::VPC::Id
  SecurityGroup:
    Default: ''
    Description: Which security groups to use
    Type: List<AWS::EC2::SecurityGroup::Id>    
Resources:
  albListenerHTTP:
    Type: AWS::ElasticLoadBalancingV2::Listener    
    Properties:
      DefaultActions:
        - Type: redirect
          RedirectConfig:
            Protocol: "HTTPS"
            Host: "#{host}"
            Port: "443"
            Path: "/#{path}"
            Query: "#{query}"
            StatusCode: HTTP_301
      LoadBalancerArn:
        Ref: applicationLoadBalancer
      Port: 80
      Protocol: HTTP
  albListenerHTTPS:
    Type: AWS::ElasticLoadBalancingV2::Listener    
    Properties:
      DefaultActions:
        - Type: redirect
          RedirectConfig:
            Protocol: "#{protocol}"
            Host: "#{host}"
            Port: "#{port}"
            Path: "/release/"
            Query: "#{query}"
            StatusCode: HTTP_301
      LoadBalancerArn:
        Ref: applicationLoadBalancer
      Port: 443
      Protocol: HTTPS
      Certificates:
        - CertificateArn:
            Ref: CertificateArn
  # N.B.: A rule like albListenerRuleXLDForward is not needed for XL Release
  # because the default action takes care of that
  albListenerRuleXLDForward:
    Type: AWS::ElasticLoadBalancingV2::ListenerRule    
    Properties:
      Conditions:
        - Field: path-pattern
          Values:
            - /deploy
      Actions:
        - Type: redirect
          RedirectConfig:
            Protocol: "#{protocol}"
            Host: "#{host}"
            Port: "#{port}"
            Path: "/deploy/"
            StatusCode: HTTP_301
      ListenerArn:
        Ref: albListenerHTTPS
      Priority: 1
  albListenerRuleXLD:
    Type: AWS::ElasticLoadBalancingV2::ListenerRule    
    Properties:
      Conditions:
        - Field: path-pattern
          Values:
            - /deploy/*
      Actions:
        - Type: forward
          TargetGroupArn:
            Ref: albTargetGroupXLD
      ListenerArn:
        Ref: albListenerHTTPS
      Priority: 2
  albListenerRuleXLR:
    Type: AWS::ElasticLoadBalancingV2::ListenerRule
    Properties:
      Conditions:
        - Field: path-pattern
          Values:
            - /release/*
      Actions:
        - Type: forward
          TargetGroupArn:
            Ref: albTargetGroupXLR
      ListenerArn:
        Ref: albListenerHTTPS
      Priority: 3
  albTargetGroupXLD:
    Type: AWS::ElasticLoadBalancingV2::TargetGroup    
    Properties:
      VpcId:
        Ref: VPCID
      Port:
        Ref: PortXLD
      Name:
        Ref: TargetGroupNameXLD
      Protocol: HTTP
      Matcher:
        HttpCode: 200-402
      HealthCheckProtocol: HTTP
      HealthCheckPath: /deploy/deployit/ha/health
      HealthCheckIntervalSeconds: 10
      HealthCheckTimeoutSeconds: 5
      HealthyThresholdCount: 2
      TargetGroupAttributes:
        - Key: stickiness.enabled
          Value: 'true'
        - Key: stickiness.type
          Value: lb_cookie
        - Key: stickiness.lb_cookie.duration_seconds
          Value: '86400'
  albTargetGroupXLR:
    Type: AWS::ElasticLoadBalancingV2::TargetGroup
    Properties:
      VpcId:
        Ref: VPCID
      Port:
        Ref: PortXLR
      Name:
        Ref: TargetGroupNameXLR
      Protocol: HTTP
      Matcher:
        HttpCode: 200-402
      HealthCheckProtocol: HTTP
      HealthCheckPath: /release/ha/health
      HealthCheckIntervalSeconds: 10
      HealthCheckTimeoutSeconds: 5
      HealthyThresholdCount: 2
      TargetGroupAttributes:
        - Key: stickiness.enabled
          Value: 'true'
        - Key: stickiness.type
          Value: lb_cookie
        - Key: stickiness.lb_cookie.duration_seconds
          Value: '86400'
  applicationLoadBalancer:
    Type: AWS::ElasticLoadBalancingV2::LoadBalancer
    Properties:
      Name:
        Ref: LoadBalancerName
      Scheme: internet-facing
      SecurityGroups:
        Ref: SecurityGroup
      Subnets:
        Ref: PublicSubnetIDs
Outputs:
  LoadBalancerUrlXLD:
    Description: URL for XL Deploy
    Value:
      Fn::Join:
        - ''
        - - https://
          - Fn::GetAtt:
              - applicationLoadBalancer
              - DNSName
          - '/deploy/'
  LoadBalancerUrlXLR:
    Description: URL for XL Release
    Value:
      Fn::Join:
        - ''
        - - https://
          - Fn::GetAtt:
              - applicationLoadBalancer
              - DNSName
          - '/release/'
  TargetGroupXLD:
    Description: ARN of XL Deploy TargetGroup
    Value: !Ref albTargetGroupXLD
  TargetGroupXLR:
    Description: ARN of XL Release TargetGroup
    Value: !Ref albTargetGroupXLR