AWSTemplateFormatVersion: 2010-09-09
Description: "Sub template that creates an Aurora PostgreSQL cluster.\n"
Parameters:
  DataSubnetIDs:
    Description: The subnets the Aurora cluster should be deployed to
    Type: List<AWS::EC2::Subnet::Id>
  DBAutoMinorVersionUpgrade:
    AllowedValues:
      - 'true'
      - 'false'
    Default: 'true'
    Description: Select true/false to setup Auto Minor Version upgrade
    Type: String
  DBBackupRetentionPeriod:
    Default: '7'
    Description: The number of days for which automatic DB snapshots are retained.
    Type: String
    AllowedPattern: ^[1-9][0-9]*
  DBInstanceClass:
    AllowedValues:
      - db.r4.16xlarge
      - db.r4.8xlarge
      - db.r4.4xlarge
      - db.r4.2xlarge
      - db.r4.xlarge
      - db.r4.large
    ConstraintDescription: Must select a valid database instance type.
    Default: db.r4.large
    Description: The name of the compute and memory capacity class of the DB instance.
    Type: String
  DBMasterUsername:
    AllowedPattern: '[a-zA-Z][a-zA-Z0-9]*'
    ConstraintDescription: must begin with a letter and contain only alphanumeric
      characters.
    Default: xladmin
    Description: The database admin account username
    MaxLength: '16'
    MinLength: '1'
    Type: String
  DBMasterPassword:
    AllowedPattern: (?=\S)[^@/"\r\n\t\f\s]*
    ConstraintDescription: Min 8 alphanumeric. Cannot contain white space, @, /, "
    Description: The database admin account password
    MaxLength: '41'
    MinLength: '8'
    NoEcho: true
    Type: String
  DBMultiAZ:
    AllowedValues:
      - 'true'
      - 'false'
    Default: 'true'
    Description: Specifies if the database instance is a multiple Availability Zone
      deployment.
    Type: String
  EnvironmentName:
    Type: String
    AllowedPattern: ^[0-9a-zA-Z]+([0-9a-zA-Z-]*[0-9a-zA-Z])*$
    Description: An environment name that will be prefixed to resource names.
  VPCID:
    Type: AWS::EC2::VPC::Id
    Description: The VPC ID the Security Groups should be deployed to
Conditions:
  CreateReadReplica:
    Fn::Equals:
      - Ref: DBMultiAZ
      - true
Resources:
  AuroraRDSSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Secure access to the RDS database by allowing only XebiaLabs
        ASGs
      VpcId:
        Ref: VPCID
      Tags:
        - Key: Name
          Value:
            Fn::Sub: ${EnvironmentName}-RDS
  RDSIngressSelf:
    Type: AWS::EC2::SecurityGroupIngress
    Properties:
      GroupId:
        Ref: AuroraRDSSecurityGroup
      SourceSecurityGroupId:
        Ref: AuroraRDSSecurityGroup
      IpProtocol: '-1'
  AuroraDBSubnetGroup:
    Type: AWS::RDS::DBSubnetGroup
    Properties:
      DBSubnetGroupDescription: Subnets available for the RDS Aurora DB Instance
      SubnetIds:
        Ref: DataSubnetIDs
  AuroraDBCluster:
    Type: AWS::RDS::DBCluster
    Properties:
      BackupRetentionPeriod:
        Ref: DBBackupRetentionPeriod
      DBSubnetGroupName:
        Ref: AuroraDBSubnetGroup
      Engine: aurora-postgresql
      EngineVersion: 9.6.9
      DBClusterParameterGroupName: default.aurora-postgresql9.6
      MasterUsername:
        Ref: DBMasterUsername
      MasterUserPassword:
        Ref: DBMasterPassword
      Port: 5432
      VpcSecurityGroupIds:
        - Ref: AuroraRDSSecurityGroup
  AuroraDBPrimaryInstance:
    Type: AWS::RDS::DBInstance
    Properties:
      Engine: aurora-postgresql
      EngineVersion: 9.6.9
      DBParameterGroupName: default.aurora-postgresql9.6
      DBClusterIdentifier:
        Ref: AuroraDBCluster
      DBInstanceClass:
        Ref: DBInstanceClass
      DBSubnetGroupName:
        Ref: AuroraDBSubnetGroup
      AutoMinorVersionUpgrade:
        Ref: DBAutoMinorVersionUpgrade
  AuroraDBSecondaryInstance:
    Type: AWS::RDS::DBInstance
    Condition: CreateReadReplica
    Properties:
      Engine: aurora-postgresql
      EngineVersion: 9.6.9
      DBParameterGroupName: default.aurora-postgresql9.6
      DBClusterIdentifier:
        Ref: AuroraDBCluster
      DBInstanceClass:
        Ref: DBInstanceClass
      DBSubnetGroupName:
        Ref: AuroraDBSubnetGroup
      AutoMinorVersionUpgrade:
        Ref: DBAutoMinorVersionUpgrade
Outputs:
  AuroraEndPointAddress:
    Description: Aurora Endpoint to connect
    Value:
      Fn::GetAtt:
        - AuroraDBCluster
        - Endpoint.Address
  AuroraEndPointPort:
    Description: Aurora Endpoint to connect
    Value:
      Fn::GetAtt:
        - AuroraDBCluster
        - Endpoint.Port
  AuroraRDSSecurityGroupID:
    Description: A reference to the security group for RDS
    Value:
      Ref: AuroraRDSSecurityGroup
