---
AWSTemplateFormatVersion: 2010-09-09
Description: >
  This template will setup the XebiaLabs DevOps Platform in a newly created VPC and RDS.
Metadata:
  'AWS::CloudFormation::Interface':
    ParameterGroups:
      - Label:
          default: Network Configuration
        Parameters:
          - CertificateArn
      - Label:
          default: XebiaLabs DevOps Platform Configuration
        Parameters:
          - XLPlatformInstanceType
          - KeyPairName
          - XLDeployPassword
          - XLReleasePassword
      - Label:
          default: RDS Configuration
        Parameters:
          - DBMasterUsername
          - DBMasterPassword
    ParameterLabels:
      XLPlatformInstanceType:
        default: XL instance type
      KeyPairName:
        default: KeyPair name for XebiaLabs software
      XLDeployPassword:
        default: XL Deploy administrator password
      XLReleasePassword:
        default: XL Release administrator password
      DBMasterUsername:
        default: Database administrator username
      DBMasterPassword:
        default: Database administrator password
      EnvironmentName:
        default: Environment name
      QSS3BucketName:
        default: Quick Start S3 bucket name
      QSS3KeyPrefix:
        default: Quick Start S3 key prefix
Parameters:
  CertificateArn:
    Description: Which ACM certificate to use for the load balancer
    Type: String
  OperatorEMail:
    Description: EMail address to notify if there are any scaling operations
    Type: String
    Default: operator@company.com
    AllowedPattern: ([a-zA-Z0-9_\-\.]+)@((\[[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.)|(([a-zA-Z0-9\-]+\.)+))([a-zA-Z]{2,4}|[0-9]{1,3})(\]?)
    ConstraintDescription: must be a valid email address.
  XLPlatformInstanceType:
    AllowedValues:
      - t2.medium
      - m5.large
      - m5.xlarge
    Description: The instance type the XL DevOps Platform applications are created on
    Type: String
    Default: t2.medium
  XLDeployPassword:
    Description: The admin password of XL Deploy
    MinLength: 8
    Type: String
    NoEcho: True
    Default: Welcome2XebiaLabs
  XLReleasePassword:
    Description: The admin password of XL Release
    MinLength: 8
    Type: String
    NoEcho: True
    Default: Welcome2XebiaLabs
  QSS3BucketName:
    AllowedPattern: '^[0-9a-zA-Z]+([0-9a-zA-Z-]*[0-9a-zA-Z])*$'
    ConstraintDescription: >-
      Quick Start bucket name can include numbers, lowercase letters, uppercase
      letters, and hyphens (-). It cannot start or end with a hyphen (-).
    Default: aws-quickstart
    Description: >-
      S3 bucket name for the Quick Start assets. Quick Start bucket name can
      include numbers, lowercase letters, uppercase letters, and hyphens (-). It
      cannot start or end with a hyphen (-).
    Type: String
  QSS3KeyPrefix:
    AllowedPattern: '^[0-9a-zA-Z-/]*$'
    ConstraintDescription: >-
      Quick Start key prefix can include numbers, lowercase letters, uppercase
      letters, hyphens (-), and forward slash (/).
    Default: ami-xebialabs-devops-platform/
    Description: >-
      S3 key prefix for the Quick Start assets. Quick Start key prefix can
      include numbers, lowercase letters, uppercase letters, hyphens (-), and
      forward slash (/).
    Type: String
  KeyPairName:
    Description: The name of an existing public/private key pair, which allows you to securely connect to your instance after it launches
    Type: AWS::EC2::KeyPair::KeyName
  EnvironmentName:
    AllowedPattern: '^[0-9a-zA-Z]+(-*[0-9a-zA-Z]+)*$'
    Description: 'The Environment name, defaults to ''xebialabs-aws''.'
    Type: String
    Default: xebialabs-aws
  CIDRBlockVpc:
    Default: "10.0.0.0/19"
    Type: String
    Description: "Enter a valid /19 cidr block."
    AllowedPattern: '((\d{1,3})\.){3}\d{1,3}/19'
  YourHomeIPRange:
    Default: "0.0.0.0/0"
    Type: String
    Description: "Enter a valid cidr block to allow traffic to SSH."
    AllowedPattern: '((\d{1,3})\.){3}\d{1,3}/\d{1,2}'
  DBMasterUsername:
    AllowedPattern: '[a-zA-Z][a-zA-Z0-9]*'
    ConstraintDescription: must begin with a letter and contain only alphanumeric characters.
    Default: xladmin
    Description: The database admin account username
    MaxLength: '16'
    MinLength: '1'
    Type: String
  DBMasterPassword:
    AllowedPattern: "(?=\\S)[^@/\"\\r\\n\\t\\f\\s]*"
    ConstraintDescription: 'Min 8 alphanumeric. Cannot contain white space, @, /, "'
    Description: The database admin account password
    MaxLength: '41'
    MinLength: '8'
    NoEcho: True
    Type: String
    Default: 'Welcome2XebiaLabs'
  DBInstanceClass:
    AllowedValues:
      - db.r4.16xlarge
      - db.r4.8xlarge
      - db.r4.4xlarge
      - db.r4.2xlarge
      - db.r4.xlarge
      - db.r4.large
    ConstraintDescription: Must select a valid database instance type.
    Default: db.r4.large
    Description: The name of the compute and memory capacity class of the DB instance.
    Type: String
  DBBackupRetentionPeriod:
    Default: 1
    Description: The number of days for which automatic DB snapshots are retained.
    Type: String
    AllowedPattern: '^[1-9][0-9]*'
  DBAutoMinorVersionUpgrade:
    AllowedValues:
      - 'true'
      - 'false'
    Default: 'true'
    Description: Select true/false to setup Auto Minor Version upgrade
    Type: String
Conditions:
  GovCloudCondition: !Equals [ !Ref "AWS::Region", us-gov-west-1 ]
Resources:
  VPCStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub
        - https://${QSS3BucketName}.${QSS3Region}.amazonaws.com/${QSS3KeyPrefix}templates/infrastructure/vpc.yaml
        - { QSS3Region: !If [GovCloudCondition, s3-us-gov-west-1, s3] }
      Parameters:
        CIDRBlockVpc: !Ref CIDRBlockVpc
        YourHomeIPRange: !Ref YourHomeIPRange
  RDSStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub
        - https://${QSS3BucketName}.${QSS3Region}.amazonaws.com/${QSS3KeyPrefix}templates/infrastructure/rds.yaml
        - { QSS3Region: !If [GovCloudCondition, s3-us-gov-west-1, s3] }
      Parameters:
        VPCID: !GetAtt VPCStack.Outputs.VPCID
        DataSubnetIDs: !GetAtt VPCStack.Outputs.DataSubnetIDs
        EnvironmentName: !Ref EnvironmentName
        DBMasterUsername: !Ref DBMasterUsername
        DBMasterPassword: !Ref DBMasterPassword
        DBInstanceClass: !Ref DBInstanceClass
        DBBackupRetentionPeriod: !Ref DBBackupRetentionPeriod
        DBAutoMinorVersionUpgrade: !Ref DBAutoMinorVersionUpgrade
  XLDevOpsPlatformStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub
        - https://${QSS3BucketName}.${QSS3Region}.amazonaws.com/${QSS3KeyPrefix}templates/install-xl-platform-existing-vpc.yaml
        - { QSS3Region: !If [GovCloudCondition, s3-us-gov-west-1, s3] }
      Parameters:
        OperatorEMail: !Ref OperatorEMail
        CertificateArn: !Ref CertificateArn
        VPCID: !GetAtt VPCStack.Outputs.VPCID
        PublicSubnetIDs: !GetAtt VPCStack.Outputs.PublicSubnetIDs
        PrivateSubnetIDs: !GetAtt VPCStack.Outputs.PrivateSubnetIDs
        XLPlatformInstanceType: !Ref XLPlatformInstanceType
        XLDeployPassword: !Ref XLDeployPassword
        XLReleasePassword: !Ref XLReleasePassword
        RDSSecurityGroupID: !GetAtt RDSStack.Outputs.AuroraRDSSecurityGroupID
        DBHost: !GetAtt RDSStack.Outputs.AuroraEndPointAddress
        DBPort: !GetAtt RDSStack.Outputs.AuroraEndPointPort
        DBUsername: !Ref DBMasterUsername
        DBPassword: !Ref DBMasterPassword
        QSS3BucketName: !Ref QSS3BucketName
        QSS3KeyPrefix: !Ref QSS3KeyPrefix
        KeyPairName: !Ref KeyPairName
        EnvironmentName: !Ref EnvironmentName
        # TO BE CHANGED TO CORRECT SG
        BastionSecurityGroupID: !GetAtt RDSStack.Outputs.AuroraRDSSecurityGroupID

Outputs:
  XLDeployURL:
    Description: The URL where XL Deploy is reachable
    Value: !GetAtt XLDevOpsPlatformStack.Outputs.XLDeployURL
  XLReleaseURL:
    Description: The URL where XL Release is reachable
    Value: !GetAtt XLDevOpsPlatformStack.Outputs.XLReleaseURL
