---
AWSTemplateFormatVersion: 2010-09-09
Description: >
  This template will setup XebiaLabs DevOps Platform in an existing VPC with an RDS.
Metadata:
  'AWS::CloudFormation::Interface':
    ParameterGroups:
      - Label:
          default: Network Configuration
        Parameters:
          - VPCID
          - PrivateSubnetIDs
          - PublicSubnetIDs
          - CertificateArn
      - Label:
          default: XebiaLabs DevOps Platform Configuration
        Parameters:
          - XLPlatformInstanceType
          - XLDeployPassword
          - XLReleasePassword
          - XLDASGInstanceName
          - XLRASGInstanceName
      - Label:
          default: RDS Configuration
        Parameters:
          - RDSSecurityGroupID
          - DBHost
          - DBPort
          - DBUsername
          - DBPassword
      - Label:
          default: Bastion Host Configuration
        Parameters:
          - BastionSecurityGroupID
      - Label:
          default: S3 Configuration
        Parameters:
          - BucketName
          - BucketKeyPrefix
      - Label:
          default: General Settings
        Parameters:
          - EnvironmentName
          - KeyPairName
    ParameterLabels:
      CertificateArn:
        default: Which ACM certificate to use for the load balancer
      VPCID:
        default: VPC ID
      PublicSubnetIDs:
        default: Public subnets
      PrivateSubnetIDs:
        default: Private subnets
      XLPlatformInstanceType:
        default: XL instance type
      KeyPairName:
        default: KeyPair name for XebiaLabs software
      XLDeployPassword:
        default: XL Deploy administrator password
      XLReleasePassword:
        default: XL Release administrator password
      XLDASGInstanceName:
        default: XL Deploy Auto-scaling Group name
      XLRASGInstanceName:
        default: XL Release Auto-scaling Group name
      RDSSecurityGroupID:
        default: RDS Security Group ID
      DBHost:
        default: Database hostname
      DBPort:
        default: Database port
      DBUsername:
        default: Database administrator username
      DBPassword:
        default: Database administrator password
      BastionSecurityGroupID:
        default: Bastion Host security group ID
      EnvironmentName:
        default: Environment name
      BucketName:
        default:  S3 bucket name
      BucketKeyPrefix:
        default: S3 key prefix
Parameters:
  CertificateArn:
    Description: Which ACM certificate to use for the load balancer
    Type: String
  VPCID:
    Description: ID of the VPC (e.g., vpc-0343606e)
    Type: AWS::EC2::VPC::Id
  PublicSubnetIDs:
    Description: The public subnet XL should reachable on
    Type: List<AWS::EC2::Subnet::Id>
  PrivateSubnetIDs:
    Description: The private subnet XL should be deployed to
    Type: List<AWS::EC2::Subnet::Id>
  XLDASGInstanceName:
    Description: ASG instances name
    Type: String
    Default: xl-deploy-asg
  XLRASGInstanceName:
    Description: ASG instances name
    Type: String
    Default: xl-release-asg
  XLPlatformInstanceType:
    Default: t2.medium
    AllowedValues:
      - t2.medium
      - c5.large
      - c5.xlarge
      - m5.large
    Description: The instance type the XL DevOps Platform applications are created on
    Type: String
  XLDeployPassword:
    Description: The admin password of XL Deploy
    MinLength: 8
    Type: String
    NoEcho: True
    Default: Welcome2XebiaLabs
  XLReleasePassword:
    Description: The admin password of XL Release
    MinLength: 8
    Type: String
    NoEcho: True
    Default: Welcome2XebiaLabs
  RDSSecurityGroupID:
    Type: 'AWS::EC2::SecurityGroup::Id'
    Description: The Security Group ID with RDS network access rules
  DBHost:
    Description: The Postgres DB Host/Endpoint
    Type: String
  DBPort:
    Description: The Postgres DB Portsu
    Type: String
    Default: 5432
  DBUsername:
    Description: The Postgres DB username
    Type: String
    Default: xladmin
  DBPassword:
    Description: The Postgres DB Password
    Type: String
    NoEcho: True
    Default: Welcome2XebiaLabs
  BucketName:
    AllowedPattern: '^[0-9a-zA-Z]+([0-9a-zA-Z-]*[0-9a-zA-Z])*$'
    ConstraintDescription: >-
      Bucket name can include numbers, lowercase letters, uppercase
      letters, and hyphens (-). It cannot start or end with a hyphen (-).
    Default: aws-quickstart
    Description: >-
      S3 bucket name for CFN . Bucket name can
      include numbers, lowercase letters, uppercase letters, and hyphens (-). It
      cannot start or end with a hyphen (-).
    Type: String
  BucketKeyPrefix:
    AllowedPattern: '^[0-9a-zA-Z-/]*$'
    ConstraintDescription: >-
      S3 bucket key prefix can include numbers, lowercase letters, uppercase
      letters, hyphens (-), and forward slash (/).
    Default: ami-xebialabs-devops-platform/
    Description: >-
      S3 bucket key prefix for CFN. Quick Start key prefix can
      include numbers, lowercase letters, uppercase letters, hyphens (-), and
      forward slash (/).
    Type: String
  KeyPairName:
    Description: The name of an existing public/private key pair, which allows you to securely connect to your instance after it launches
    Type: AWS::EC2::KeyPair::KeyName
  BastionSecurityGroupID:
    Description: Bastion Host security group ID
    Type: AWS::EC2::SecurityGroup::Id
  EnvironmentName:
    AllowedPattern: '^[0-9a-zA-Z]+(-*[0-9a-zA-Z]+)*$'
    Description: 'The Environment name, defaults to ''xebialabs-aws''.'
    Type: String
    Default: xebialabs-aws

Mappings:
  AWSRegionAMI:
    eu-central-1:
      AMIID: ami-0d474a9df1f1f7a51
    eu-north-1:
      AMIID: ami-0cfe325c7e63d74d7
    eu-west-1:
      AMIID: ami-016efc83a75038991
    eu-west-2:
      AMIID: ami-02f504e8a97a6b7e9
    eu-west-3:
      AMIID: ami-04dc46236d6216b85
    us-east-1:
      AMIID: ami-00d1d67f95a8cd2aa
    us-east-2:
      AMIID: ami-0800eab6d027a79a1
    us-west-1:
      AMIID: ami-0e09bcbd79f28d49f
    us-west-2:
      AMIID: ami-032a5a2e76d197150
Conditions:
  GovCloudCondition: !Equals [ !Ref "AWS::Region", us-gov-west-1 ]
Resources:
  SecurityGroupsStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub
      - https://${BucketName}.${S3Region}.amazonaws.com/${BucketKeyPrefix}templates/infrastructure/securitygroups.yaml
      - { S3Region: !If [GovCloudCondition, s3-us-gov-west-1, s3] }
      Parameters:
        EnvironmentName: !Ref EnvironmentName
        VPCID: !Ref VPCID
        RDSSecurityGroupID: !Ref RDSSecurityGroupID
        BastionSecurityGroupID: !Ref BastionSecurityGroupID
  RDSCreateDBLambda:
   Type: AWS::CloudFormation::Stack
   Properties:
     TemplateURL: !Sub
     - https://${BucketName}.${S3Region}.amazonaws.com/${BucketKeyPrefix}templates/infrastructure/rds-lambda.yaml
     - { S3Region: !If [GovCloudCondition, s3-us-gov-west-1, s3] }
     Parameters:
       PrivateSubnetIDs: !Join [ ",", !Ref PrivateSubnetIDs ]
       DBUser: !Ref DBUsername
       DBPassword: !Ref DBPassword
       DBHost: !Ref DBHost
       AuroraRDSSecurityGroupID: !Ref RDSSecurityGroupID
       BucketName: !Ref BucketName
       BucketKeyPrefix: !Ref BucketKeyPrefix
  EFSStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub
      - https://${BucketName}.${S3Region}.amazonaws.com/${BucketKeyPrefix}templates/infrastructure/efs.yaml
      - { S3Region: !If [GovCloudCondition, s3-us-gov-west-1, s3] }
      Parameters:
        EnvironmentName: !Ref EnvironmentName
        VPCID: !Ref VPCID
        XLDeployASGSecurityGroup: !GetAtt SecurityGroupsStack.Outputs.XLDeployASGSecurityGroup
        XLReleaseASGSecurityGroup: !GetAtt SecurityGroupsStack.Outputs.XLReleaseASGSecurityGroup
        PrivateSubnetIDs: !Join [ ",", !Ref PrivateSubnetIDs ]
  LoadBalancerStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub
      - https://${BucketName}.${S3Region}.amazonaws.com/${BucketKeyPrefix}templates/infrastructure/alb.yaml
      - { S3Region: !If [GovCloudCondition, s3-us-gov-west-1, s3] }
      Parameters:
        LoadBalancerName: !Ref EnvironmentName
        VPCID: !Ref VPCID
        PublicSubnetIDs: !Join [ ",", !Ref PublicSubnetIDs ]
        SecurityGroup: !GetAtt SecurityGroupsStack.Outputs.LoadBalancerSecurityGroup
        CertificateArn: !Ref CertificateArn
  XLDeployStack:
   Type: 'AWS::CloudFormation::Stack'
   Properties:
     TemplateURL: !Sub
     - https://${BucketName}.${S3Region}.amazonaws.com/${BucketKeyPrefix}templates/services/xl-deploy.yaml
     - { S3Region: !If [GovCloudCondition, s3-us-gov-west-1, s3] }
     Parameters:
       ASGInstanceName: !Ref XLDASGInstanceName
       PrivateSubnetIDs: !Join [ ",", !Ref PrivateSubnetIDs ]
       KeyPairName: !Ref KeyPairName
       XLDeployAdminPassword: !Ref XLDeployPassword
       TargetGroupARN: !GetAtt LoadBalancerStack.Outputs.TargetGroupXLD
       SecurityGroup: !GetAtt SecurityGroupsStack.Outputs.XLDeployASGSecurityGroup
       DBHost: !Ref DBHost
       DBPort: !Ref DBPort
       DBUser: !Ref DBUsername
       DBPassword: !Ref DBPassword
       AMIID: !FindInMap [AWSRegionAMI, !Ref 'AWS::Region', AMIID]
       EfsId: !GetAtt EFSStack.Outputs.FilesystemXLD
       XLDeployInstanceType: !Ref XLPlatformInstanceType
       # TO BE CHANGED WITH REAL PRODUCT CODE
       AWSProductCode: TODO-123456789
  XLReleaseStack:
    Type: 'AWS::CloudFormation::Stack'
    Properties:
      TemplateURL: !Sub
      - https://${BucketName}.${S3Region}.amazonaws.com/${BucketKeyPrefix}templates/services/xl-release.yaml
      - { S3Region: !If [GovCloudCondition, s3-us-gov-west-1, s3] }
      Parameters:
        ASGInstanceName: !Ref XLRASGInstanceName
        PrivateSubnetIDs: !Join [ ",", !Ref PrivateSubnetIDs ]
        KeyPairName: !Ref KeyPairName
        XLReleaseAdminPassword: !Ref XLReleasePassword
        TargetGroupARN: !GetAtt LoadBalancerStack.Outputs.TargetGroupXLR
        SecurityGroup: !GetAtt SecurityGroupsStack.Outputs.XLReleaseASGSecurityGroup
        DBHost: !Ref DBHost
        DBPort: !Ref DBPort
        DBUser: !Ref DBUsername
        DBPassword: !Ref DBPassword
        ReportingDBHost: !Ref DBHost
        ReportingDBPort: !Ref DBPort
        ReportingDBUser: !Ref DBUsername
        ReportingDBPassword: !Ref DBPassword
        AMIID: !FindInMap [AWSRegionAMI, !Ref 'AWS::Region', AMIID]
        XLReleaseInstanceType: !Ref XLPlatformInstanceType
        EfsId: !GetAtt EFSStack.Outputs.FilesystemXLR
        # TO BE CHANGED WITH REAL PRODUCT CODE
        AWSProductCode: TODO-123456789
  CloudWatchDashboard:
    Type: 'AWS::CloudFormation::Stack'
    Properties:
      TemplateURL: !Sub
      - https://${BucketName}.${S3Region}.amazonaws.com/${BucketKeyPrefix}templates/infrastructure/cw-dashboard.yaml
      - { S3Region: !If [GovCloudCondition, s3-us-gov-west-1, s3] }
      Parameters:
        XLDASGInstanceName: !Ref XLDASGInstanceName
        XLRASGInstanceName: !Ref XLRASGInstanceName
  MonitoringStack:
    Type: 'AWS::CloudFormation::Stack'
    Properties:
      TemplateURL: !Sub
      - https://${BucketName}.${S3Region}.amazonaws.com/${BucketKeyPrefix}templates/infrastructure/cloudwatch.yaml
      - { S3Region: !If [GovCloudCondition, s3-us-gov-west-1, s3] }
      Parameters:
        LoadBalancerARN: !GetAtt LoadBalancerStack.Outputs.LoadBalancerARN
        XLDTargetGroupARN: !GetAtt LoadBalancerStack.Outputs.TargetGroupXLD
        XLDASGName: !GetAtt XLDeployStack.Outputs.XLDASGName
        XLDASGInstanceName: !Ref XLDASGInstanceName
        XLRASGInstanceName: !Ref XLRASGInstanceName
        XLRTargetGroupARN: !GetAtt LoadBalancerStack.Outputs.TargetGroupXLR
        XLRASGName: !GetAtt XLReleaseStack.Outputs.XLRASGName
Outputs:
  XLDeployURL:
    Description: The URL where XL Deploy is reachable
    Value: !GetAtt LoadBalancerStack.Outputs.LoadBalancerUrlXLD
  XLReleaseURL:
    Description: The URL where XL Release is reachable
    Value: !GetAtt LoadBalancerStack.Outputs.LoadBalancerUrlXLR
