---
AWSTemplateFormatVersion: 2010-09-09
Description: >
  This template will setup the XebiaLabs DevOps Platform in a newly created VPC and RDS.
Metadata:
  'AWS::CloudFormation::Interface':
    ParameterGroups:
      - Label:
          default: Network Configuration
        Parameters:
          - CertificateArn
          - CIDRBlockVpc
          - RemoteAccessCIDR
      - Label:
          default: XebiaLabs DevOps Platform Configuration
        Parameters:
          - XLPlatformInstanceType
          - XLDeployPassword
          - XLReleasePassword
          - XLDASGInstanceName
          - XLRASGInstanceName
      - Label:
          default: RDS Configuration
        Parameters:
          - DBMasterUsername
          - DBMasterPassword
          - DBInstanceClass
          - DBBackupRetentionPeriod
          - DBAutoMinorVersionUpgrade
      - Label:
          default: S3 Configuration
        Parameters:
          - BucketName
          - BucketKeyPrefix
      - Label:
          default: General Settings
        Parameters:
          - EnvironmentName
          - KeyPairName
    ParameterLabels:
      CIDRBlockVpc:
        default: cidr block
      CertificateArn:
        default: Which ACM certificate to use for the load balancer
      RemoteAccessCIDR:
        default: Remote access CIDR
      XLPlatformInstanceType:
        default: XL instance type
      KeyPairName:
        default: KeyPair name for XebiaLabs software
      XLDASGInstanceName:
        default: Auto-scaling group name for XL Deploy
      XLRASGInstanceName:
        default: Auto-scaling group name for XL Release
      XLDeployPassword:
        default: XL Deploy administrator password
      XLReleasePassword:
        default: XL Release administrator password
      DBMasterUsername:
        default: Database administrator username
      DBMasterPassword:
        default: Database administrator password
      DBInstanceClass:
        default: DB instance type
      DBBackupRetentionPeriod:
        default: The number of days for which automatic DB snapshots are retained
      DBAutoMinorVersionUpgrade:
        default: Whenever to allow Auto Minor Version upgrade or not
      EnvironmentName:
        default: Environment name
      BucketName:
        default: S3 bucket name
      BucketKeyPrefix:
        default: S3 key prefix
Parameters:
  CertificateArn:
    Description: Which ACM certificate to use for the load balancer
    Type: String
  XLPlatformInstanceType:
    AllowedValues:
      - t2.medium
      - c5.large
      - c5.xlarge
      - m5.large
      - m5.2xlarge
    Description: The instance type the XL DevOps Platform applications are created on
    Type: String
    Default: t2.medium
  XLDeployPassword:
    Description: The admin password of XL Deploy
    MinLength: 8
    Type: String
    NoEcho: True
  XLReleasePassword:
    Description: The admin password of XL Release
    MinLength: 8
    Type: String
    NoEcho: True
  BucketName:
    AllowedPattern: '^[0-9a-zA-Z]+([0-9a-zA-Z-]*[0-9a-zA-Z])*$'
    ConstraintDescription: >-
      Bucket name can include numbers, lowercase letters, uppercase
      letters, and hyphens (-). It cannot start or end with a hyphen (-).
    Default: aws-quickstart
    Description: >-
      S3 bucket name for CFN . Bucket name can
      include numbers, lowercase letters, uppercase letters, and hyphens (-). It
      cannot start or end with a hyphen (-).
    Type: String
  BucketKeyPrefix:
    AllowedPattern: '^[0-9a-zA-Z-/]*$'
    ConstraintDescription: >-
      S3 bucket key prefix can include numbers, lowercase letters, uppercase
      letters, hyphens (-), and forward slash (/).
    Default: ami-xebialabs-devops-platform/
    Description: >-
      S3 bucket key prefix for CFN. Quick Start key prefix can
      include numbers, lowercase letters, uppercase letters, hyphens (-), and
      forward slash (/).
    Type: String
  KeyPairName:
    Description: The name of an existing public/private key pair, which allows you to securely connect to your instance after it launches
    Type: AWS::EC2::KeyPair::KeyName
  EnvironmentName:
    AllowedPattern: '^[0-9a-zA-Z]+(-*[0-9a-zA-Z]+)*$'
    Description: 'The Environment name, defaults to ''xebialabs-aws''.'
    Type: String
    Default: xebialabs-aws
  CIDRBlockVpc:
    Default: "10.0.0.0/19"
    Type: String
    Description: "Enter a valid /19 cidr block."
    AllowedPattern: '((\d{1,3})\.){3}\d{1,3}/19'
  DBMasterUsername:
    AllowedPattern: '[a-zA-Z][a-zA-Z0-9]*'
    ConstraintDescription: must begin with a letter and contain only alphanumeric characters.
    Default: xladmin
    Description: The database admin account username
    MaxLength: '16'
    MinLength: '1'
    Type: String
  DBMasterPassword:
    AllowedPattern: "(?=\\S)[^@/\"\\r\\n\\t\\f\\s]*"
    ConstraintDescription: 'Min 8 alphanumeric. Cannot contain white space, @, /, "'
    Description: The database admin account password
    MaxLength: '41'
    MinLength: '8'
    NoEcho: True
    Type: String
  DBInstanceClass:
    AllowedValues:
      - db.r4.16xlarge
      - db.r4.8xlarge
      - db.r4.4xlarge
      - db.r4.2xlarge
      - db.r4.xlarge
      - db.r4.large
    ConstraintDescription: Must select a valid database instance type.
    Default: db.r4.large
    Description: The name of the compute and memory capacity class of the DB instance.
    Type: String
  DBBackupRetentionPeriod:
    Default: 1
    Description: The number of days for which automatic DB snapshots are retained.
    Type: String
    AllowedPattern: '^[1-9][0-9]*'
  DBAutoMinorVersionUpgrade:
    AllowedValues:
      - 'true'
      - 'false'
    Default: 'true'
    Description: Select true/false to setup Auto Minor Version upgrade
    Type: String
  RemoteAccessCIDR:
    AllowedPattern: "^(([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])\\.){3}([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])(\\/([0-9]|[1-2][0-9]|3[0-2]))$"
    Description: "Ip range off your home network from where you can access the bastion hosts"
    Type: String
    Default: '0.0.0.0/0'
  XLRASGInstanceName:
    Description: Auto-scaling group name for XL Release
    Type: String
    Default: xl-release-asg
  XLDASGInstanceName:
    Description: Auto-scaling group name for XL Deploy
    Type: String
    Default: xl-deploy-asg
  BastionInstanceType:
    AllowedValues:
      - t2.micro
    Default: t2.micro
    Description: Amazon EC2 instance type for the bastion instances
    Type: String

Conditions:
  GovCloudCondition: !Equals [ !Ref "AWS::Region", us-gov-west-1 ]

Mappings:
  AWSRegionAMI:
    us-east-1:
      AMIID: ami-08e0c390dfac36c29
    us-east-2:
      AMIID: ami-0800eab6d027a79a1
    us-west-1:
      AMIID: ami-0e09bcbd79f28d49f
    us-west-2:
      AMIID: ami-032a5a2e76d197150
    ap-northeast-1:
      AMIID: ami-032a5a2e76d197150
    ap-northeast-2:
      AMIID: ami-032a5a2e76d197150
    ap-south-1:
      AMIID: ami-032a5a2e76d197150
    ap-southeast-1:
      AMIID: ami-032a5a2e76d197150
    ap-southeast-2:
      AMIID: ami-032a5a2e76d197150
    ca-central-1:
      AMIID: ami-032a5a2e76d197150
    eu-central-1:
      AMIID: ami-032a5a2e76d197150
    eu-west-1:
      AMIID: ami-032a5a2e76d197150
    eu-west-2:
      AMIID: ami-032a5a2e76d197150
    eu-west-3:
      AMIID: ami-0d474a9df1f1f7a51

Resources:
  VPCStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub
        - https://${BucketName}.${S3Region}.amazonaws.com/${BucketKeyPrefix}templates/infrastructure/vpc.yaml
        - { S3Region: !If [GovCloudCondition, s3-us-gov-west-1, s3] }
      Parameters:
        CIDRBlockVpc: !Ref CIDRBlockVpc
        RemoteAccessCIDR: !Ref RemoteAccessCIDR
  BastionStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub
        - https://${BucketName}.${S3Region}.amazonaws.com/${BucketKeyPrefix}templates/infrastructure/bastion.yaml
        - { S3Region: !If [GovCloudCondition, s3-us-gov-west-1, s3] }
      Parameters:
        VPCID: !GetAtt VPCStack.Outputs.VPCID
        PublicSubnetIDs: !GetAtt VPCStack.Outputs.PublicSubnetIDs
        KeyPairName: !Ref KeyPairName
        RemoteAccessCIDR: !Ref RemoteAccessCIDR
        AMIID: !FindInMap [AWSRegionAMI, !Ref 'AWS::Region', AMIID]
        BastionInstanceType: !Ref BastionInstanceType
        EnvironmentName: !Ref EnvironmentName
  RDSStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub
        - https://${BucketName}.${S3Region}.amazonaws.com/${BucketKeyPrefix}templates/infrastructure/rds.yaml
        - { S3Region: !If [GovCloudCondition, s3-us-gov-west-1, s3] }
      Parameters:
        VPCID: !GetAtt VPCStack.Outputs.VPCID
        DataSubnetIDs: !GetAtt VPCStack.Outputs.DataSubnetIDs
        EnvironmentName: !Ref EnvironmentName
        DBMasterUsername: !Ref DBMasterUsername
        DBMasterPassword: !Ref DBMasterPassword
        DBInstanceClass: !Ref DBInstanceClass
        DBBackupRetentionPeriod: !Ref DBBackupRetentionPeriod
        DBAutoMinorVersionUpgrade: !Ref DBAutoMinorVersionUpgrade
  XLDevOpsPlatformStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub
        - https://${BucketName}.${S3Region}.amazonaws.com/${BucketKeyPrefix}templates/install-xl-platform-existing-vpc.yaml
        - { S3Region: !If [GovCloudCondition, s3-us-gov-west-1, s3] }
      Parameters:
        CertificateArn: !Ref CertificateArn
        VPCID: !GetAtt VPCStack.Outputs.VPCID
        PublicSubnetIDs: !GetAtt VPCStack.Outputs.PublicSubnetIDs
        PrivateSubnetIDs: !GetAtt VPCStack.Outputs.PrivateSubnetIDs
        XLPlatformInstanceType: !Ref XLPlatformInstanceType
        XLRASGInstanceName: !Ref XLRASGInstanceName
        XLDASGInstanceName: !Ref XLDASGInstanceName
        XLDeployPassword: !Ref XLDeployPassword
        XLReleasePassword: !Ref XLReleasePassword
        RDSSecurityGroupID: !GetAtt RDSStack.Outputs.AuroraRDSSecurityGroupID
        DBHost: !GetAtt RDSStack.Outputs.AuroraEndPointAddress
        DBPort: !GetAtt RDSStack.Outputs.AuroraEndPointPort
        DBUsername: !Ref DBMasterUsername
        DBPassword: !Ref DBMasterPassword
        BucketName: !Ref BucketName
        BucketKeyPrefix: !Ref BucketKeyPrefix
        KeyPairName: !Ref KeyPairName
        EnvironmentName: !Ref EnvironmentName
        BastionSecurityGroupID: !GetAtt BastionStack.Outputs.BastionSecurityGroup
Outputs:
  XLDeployURL:
    Description: The URL where XL Deploy is reachable
    Value: !GetAtt XLDevOpsPlatformStack.Outputs.XLDeployURL
  XLReleaseURL:
    Description: The URL where XL Release is reachable
    Value: !GetAtt XLDevOpsPlatformStack.Outputs.XLReleaseURL
  BastionPublicIP:
    Description: Elastic IP from where the Bastion can be reached
    Value: !GetAtt BastionStack.Outputs.EIP1